services:
    marketplace.test:
        build:
            context: ./docker/8.4
            args:
                WWWUSER: '${WWWUSER}'
                WWWGROUP: '${WWWGROUP}'
                SUPERVISOR_PHP_USER: 'sail'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            SUPERVISOR_PHP_USER: 'sail'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            - mariadb
